language: erlang
services:
  - mongodb
notifications:
  email:
    - zztczcx@gmail.com
otp_release:
  - 17.1
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.0.zip
  - unzip -d elixir v1.0.0.zip
before_script:
  - sleep 15
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get
script: "MIX_ENV=test mix test"
