language: erlang
services:
  - mongodb
notifications:
  email:
    - jerp@checkiz.com
otp_release:
  - 17.1
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix archive.install http://s3.hex.pm/installs/hex.ez --force
  - mix deps.get
script:
  - mix do test
